name: BYD_WORLD_ULTRA
version: '2.1.6-SNAPSHOT'
main: org.data7.bYD_WORLD_ULTRA.BYD_WORLD_ULTRA
api-version: '1.21'
author: "Data_7"
softdepend: ["PlaceholderAPI"]
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true